-- 코드를 입력하세요
SELECT ANI_IN.ANIMAL_ID, ANI_IN.ANIMAL_TYPE, ANI_IN.NAME
FROM ANIMAL_INS as ANI_IN
LEFT JOIN ANIMAL_OUTS as ANI_OUT
ON ANI_IN.ANIMAL_ID = ANI_OUT.ANIMAL_ID
WHERE ANI_IN.SEX_UPON_INTAKE != ANI_OUT.SEX_UPON_OUTCOME
ORDER BY ANI_IN.ANIMAL_ID;