-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, sum(O.SALES_AMOUNT * P.PRICE) as SALES
FROM  PRODUCT as P
JOIN OFFLINE_SALE as O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE


# SELECT PRODUCT_CODE,SUM(PRICE * SALES_AMOUNT) AS SALES FROM PRODUCT 
# JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC,PRODUCT_CODE